export const ADMIN_ROUTE_PERMISSIONS: Record<string, string> = {
  "/admin": "admin:read",
  "/admin/users": "admin:users",
  "/admin/organizations": "admin:organizations",
  "/admin/workspaces": "admin:workspaces",
  "/admin/ai-providers": "admin:ai_providers",
  "/admin/jobs": "admin:jobs",
  "/admin/queues": "admin:queues",
  "/admin/billing": "admin:billing",
  "/admin/subscriptions": "admin:subscriptions",
  "/admin/coupons": "admin:coupons",
  "/admin/analytics": "admin:analytics",
  "/admin/audit-logs": "admin:audit_logs",
  "/admin/feature-flags": "admin:feature_flags",
  "/admin/settings": "admin:system",
  "/admin/stats": "admin:stats",
  "/admin/cache": "admin:system",
};

export const ADMIN_ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    "admin:read",
    "admin:users",
    "admin:organizations",
    "admin:workspaces",
    "admin:ai_providers",
    "admin:jobs",
    "admin:queues",
    "admin:billing",
    "admin:subscriptions",
    "admin:coupons",
    "admin:analytics",
    "admin:audit_logs",
    "admin:feature_flags",
    "admin:system",
    "admin:stats",
  ],
  super_admin: [
    "admin:read",
    "admin:users",
    "admin:organizations",
    "admin:workspaces",
    "admin:ai_providers",
    "admin:jobs",
    "admin:queues",
    "admin:billing",
    "admin:subscriptions",
    "admin:coupons",
    "admin:analytics",
    "admin:audit_logs",
    "admin:feature_flags",
    "admin:system",
    "admin:stats",
  ],
};
