export const ADMIN_ROUTE_PERMISSIONS: Record<string, string> = {
  "/admin": "admin:read",
  "/admin/users": "admin:users",
  "/admin/organizations": "admin:organizations",
  "/admin/workspaces": "admin:workspaces",
  "/admin/ai-providers": "admin:ai_providers",
  "/admin/jobs": "admin:jobs",
  "/admin/queues": "admin:queues",
  "/admin/billing": "admin:billing",
  "/admin/subscriptions": "admin:subscriptions",
  "/admin/coupons": "admin:coupons",
  "/admin/analytics": "admin:analytics",
  "/admin/audit-logs": "admin:audit_logs",
  "/admin/feature-flags": "admin:feature_flags",
  "/admin/settings": "admin:system",
  "/admin/stats": "admin:stats",
  "/admin/cache": "admin:system",
  "/admin/email": "admin:email",
  "/admin/email/providers": "admin:email",
  "/admin/email/templates": "admin:email",
  "/admin/email/queue": "admin:email",
  "/admin/email/logs": "admin:email",
  "/admin/email/health": "admin:email",
  "/admin/email/statistics": "admin:email",
};

const ADMIN_PERMISSIONS = [
  "admin:read",
  "admin:users",
  "admin:organizations",
  "admin:workspaces",
  "admin:ai_providers",
  "admin:jobs",
  "admin:queues",
  "admin:billing",
  "admin:subscriptions",
  "admin:coupons",
  "admin:analytics",
  "admin:audit_logs",
  "admin:feature_flags",
  "admin:system",
  "admin:stats",
  "admin:email",
  "admin:write",
  "admin:commerce",
  "workspaces.read",
  "workspaces.write",
  "users.read",
  "users.write",
  "organizations.read",
  "organizations.write",
  "billing.write",
  "notifications.read",
  "notifications.write",
];

export const ADMIN_ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [...ADMIN_PERMISSIONS],
  super_admin: [...ADMIN_PERMISSIONS],
};
