import { pgTable, text, timestamp, boolean, index, varchar, integer, jsonb, real } from "drizzle-orm/pg-core";

export const hypercareIncident = pgTable("hypercare_incident", {
  id: text("id").primaryKey(),
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description"),
  severity: varchar("severity", { length: 50 }).default("medium").notNull(),
  priority: varchar("priority", { length: 50 }).default("medium").notNull(),
  status: varchar("status", { length: 50 }).default("open").notNull(),
  affectedModule: varchar("affected_module", { length: 100 }),
  affectedUsers: integer("affected_users").default(0).notNull(),
  ownerId: text("owner_id"),
  detectionTime: timestamp("detection_time").defaultNow().notNull(),
  resolutionTime: timestamp("resolution_time"),
  rootCause: text("root_cause"),
  technicalCause: text("technical_cause"),
  businessImpact: text("business_impact"),
  correctiveAction: text("corrective_action"),
  preventiveAction: text("preventive_action"),
  verification: text("verification"),
  lessonsLearned: text("lessons_learned"),
  relatedHotfixId: text("related_hotfix_id"),
  linkedDeploymentId: text("linked_deployment_id"),
  linkedVersion: varchar("linked_version", { length: 100 }),
  timeline: jsonb("timeline").$type<Array<{ timestamp: string; action: string; note: string; admin: string }>>().default([]).notNull(),
  affectedServices: jsonb("affected_services").$type<string[]>().default([]).notNull(),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(),
  isResolved: boolean("is_resolved").default(false).notNull(),
  closedAt: timestamp("closed_at"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hci_status_idx").on(table.status),
  index("hci_severity_idx").on(table.severity),
  index("hci_priority_idx").on(table.priority),
  index("hci_module_idx").on(table.affectedModule),
  index("hci_created_idx").on(table.createdAt),
]);

export const hypercareHotfix = pgTable("hypercare_hotfix", {
  id: text("id").primaryKey(),
  incidentId: text("incident_id"),
  branchName: varchar("branch_name", { length: 200 }).notNull(),
  commitHash: varchar("commit_hash", { length: 100 }),
  title: varchar("title", { length: 500 }).notNull(),
  description: text("description"),
  status: varchar("status", { length: 50 }).default("pending").notNull(),
  targetVersion: varchar("target_version", { length: 100 }),
  deployedAt: timestamp("deployed_at"),
  rolledBackAt: timestamp("rolled_back_at"),
  verifiedAt: timestamp("verified_at"),
  verifiedBy: text("verified_by"),
  regressionTestsPassed: boolean("regression_tests_passed").default(false).notNull(),
  validationResults: jsonb("validation_results").$type<Record<string, unknown>>().default({}).notNull(),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hfh_incident_idx").on(table.incidentId),
  index("hfh_status_idx").on(table.status),
  index("hfh_branch_idx").on(table.branchName),
]);

export const hypercareHealthCheck = pgTable("hypercare_health_check", {
  id: text("id").primaryKey(),
  serviceName: varchar("service_name", { length: 100 }).notNull(),
  serviceType: varchar("service_type", { length: 50 }).notNull(),
  status: varchar("status", { length: 50 }).default("unknown").notNull(),
  latencyMs: integer("latency_ms"),
  healthScore: real("health_score"),
  uptime: text("uptime"),
  lastCheckedAt: timestamp("last_checked_at").defaultNow().notNull(),
  lastHealthyAt: timestamp("last_healthy_at"),
  lastErrorAt: timestamp("last_error_at"),
  errorMessage: text("error_message"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hhc_service_idx").on(table.serviceName),
  index("hhc_status_idx").on(table.status),
]);

export const hypercareKpi = pgTable("hypercare_kpi", {
  id: text("id").primaryKey(),
  name: varchar("name", { length: 200 }).notNull(),
  category: varchar("category", { length: 100 }).notNull(),
  targetValue: real("target_value"),
  currentValue: real("current_value"),
  unit: varchar("unit", { length: 50 }),
  status: varchar("status", { length: 50 }).default("unknown").notNull(),
  trend: varchar("trend", { length: 50 }).default("stable").notNull(),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(),
  recordedAt: timestamp("recorded_at").defaultNow().notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hkpi_name_idx").on(table.name),
  index("hkpi_category_idx").on(table.category),
  index("hkpi_recorded_idx").on(table.recordedAt),
]);

export const hypercareFeedback = pgTable("hypercare_feedback", {
  id: text("id").primaryKey(),
  userId: text("user_id"),
  category: varchar("category", { length: 100 }).notNull(),
  type: varchar("type", { length: 50 }).notNull(),
  subject: varchar("subject", { length: 500 }).notNull(),
  content: text("content"),
  rating: integer("rating"),
  status: varchar("status", { length: 50 }).default("open").notNull(),
  linkedIncidentId: text("linked_incident_id"),
  module: varchar("module", { length: 100 }),
  priority: varchar("priority", { length: 50 }).default("medium").notNull(),
  resolvedAt: timestamp("resolved_at"),
  resolvedBy: text("resolved_by"),
  response: text("response"),
  metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hfb_category_idx").on(table.category),
  index("hfb_type_idx").on(table.type),
  index("hfb_status_idx").on(table.status),
  index("hfb_module_idx").on(table.module),
]);

export const hypercareReport = pgTable("hypercare_report", {
  id: text("id").primaryKey(),
  type: varchar("type", { length: 50 }).notNull(),
  title: varchar("title", { length: 500 }).notNull(),
  content: jsonb("content").$type<Record<string, unknown>>().default({}).notNull(),
  summary: text("summary"),
  period: varchar("period", { length: 100 }),
  status: varchar("status", { length: 50 }).default("draft").notNull(),
  generatedAt: timestamp("generated_at").defaultNow().notNull(),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hrpt_type_idx").on(table.type),
  index("hrpt_period_idx").on(table.period),
  index("hrpt_generated_idx").on(table.generatedAt),
]);

export const hypercareRootCause = pgTable("hypercare_root_cause", {
  id: text("id").primaryKey(),
  incidentId: text("incident_id").notNull(),
  problemDescription: text("problem_description"),
  detectionTime: timestamp("detection_time"),
  affectedServices: jsonb("affected_services").$type<string[]>().default([]).notNull(),
  rootCause: text("root_cause"),
  technicalCause: text("technical_cause"),
  businessImpact: text("business_impact"),
  correctiveAction: text("corrective_action"),
  preventiveAction: text("preventive_action"),
  verification: text("verification"),
  lessonsLearned: text("lessons_learned"),
  completedAt: timestamp("completed_at"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hrc_incident_idx").on(table.incidentId),
]);

export const hypercareSettings = pgTable("hypercare_settings", {
  id: text("id").primaryKey(),
  key: varchar("key", { length: 200 }).notNull(),
  value: jsonb("value").$type<Record<string, unknown>>().default({}).notNull(),
  description: text("description"),
  updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
  index("hset_key_idx").on(table.key),
]);
