export const LANDING_SECTIONS = [
  {
    id: "hero-section",
    sectionKey: "hero",
    type: "hero",
    title: "From intent to production",
    description: "Tamer Studio is the AI-first production operating system. Plan, generate, organize, review, and publish content without switching between tools.",
    order: 0,
    visible: true,
    config: {
      heading: "From intent to production",
      description: "Tamer Studio is the AI-first production operating system. Plan, generate, organize, review, and publish content without switching between tools.",
      ctaPrimary: "Get Started Free",
      ctaSecondary: "Sign In",
      showProviders: true,
    },
  },
  {
    id: "social-proof-section",
    sectionKey: "social-proof",
    type: "custom",
    title: "Trusted by creators, agencies, and businesses worldwide",
    description: "Trusted by creators, agencies, and businesses worldwide",
    order: 1,
    visible: true,
    config: {
      title: "Trusted by creators, agencies, and businesses worldwide",
      stats: [
        { label: "Projects", value: "10K+", suffix: "+" },
        { label: "Teams", value: "500+", suffix: "+" },
        { label: "AI Generations", value: "1M+", suffix: "+", display: "1M+" },
        { label: "Availability", value: "99.9%", suffix: "", display: "99.9%" },
      ],
    },
  },
  {
    id: "features-section",
    sectionKey: "features",
    type: "features",
    title: "Built for modern content teams",
    description: "Everything you need to manage the full content lifecycle in one place.",
    order: 2,
    visible: true,
    config: {
      heading: "Built for modern content teams",
      description: "Everything you need to manage the full content lifecycle in one place.",
      features: [
        { title: "Workspace", description: "Organize teams, members, and permissions across multiple workspaces.", icon: "boxes" },
        { title: "Projects", description: "Manage production projects with folders, tags, assets, and archives.", icon: "folder-open" },
        { title: "Media", description: "Generate and organize images, videos, audio, and documents in one library.", icon: "image" },
        { title: "Production", description: "Run production pipelines with queues, retries, logs, and progress tracking.", icon: "clapperboard" },
        { title: "AI Platform", description: "Connect providers, manage models, and compose prompts with unified playground.", icon: "cpu" },
        { title: "Publishing", description: "Schedule and publish content to external platforms from one hub.", icon: "play" },
        { title: "Billing", description: "Manage invoices, subscriptions, and payment methods in one place.", icon: "credit-card" },
        { title: "Analytics", description: "Track production metrics, AI usage, and team performance.", icon: "bar-chart-3" },
        { title: "Marketplace", description: "Discover and integrate community templates and plugins.", icon: "store" },
      ],
    },
  },
  {
    id: "ai-platform-section",
    sectionKey: "ai-platform",
    type: "custom",
    title: "AI Platform for Production Teams",
    description: "Connect any AI provider, compose prompts, automate workflows, and optimize costs — all from one interface.",
    order: 3,
    visible: true,
    config: {
      heading: "AI Platform for Production Teams",
      description: "Connect any AI provider, compose prompts, automate workflows, and optimize costs — all from one interface.",
      features: [
        { title: "Multi-Provider AI", description: "Connect OpenAI, Gemini, Claude, OpenRouter, Kilo, and more with a single API key.", icon: "globe" },
        { title: "Prompt Library", description: "Save, version, and reuse prompts across projects and teams.", icon: "book-open" },
        { title: "Workflow Automation", description: "Build production pipelines combining AI models, applying safeguards, and routing outputs.", icon: "workflow" },
        { title: "Model Selection", description: "Choose the right model for each task. Compare costs, latency, and quality.", icon: "sliders" },
        { title: "Cost Optimization", description: "Track spending per project, set budgets, and get alerts before exceeding limits.", icon: "dollar-sign" },
        { title: "History", description: "Every AI call is logged. Review, replay, and audit every generation.", icon: "clock" },
        { title: "Versioning", description: "Version your prompts and models. Roll back to any previous state.", icon: "git-branch" },
      ],
    },
  },
  {
    id: "screenshots-section",
    sectionKey: "screenshots",
    type: "custom",
    title: "See Tamer Studio in Action",
    description: "From dashboard to delivery, every screen is designed for production teams.",
    order: 4,
    visible: true,
    config: {
      heading: "See Tamer Studio in Action",
      description: "From dashboard to delivery, every screen is designed for production teams.",
      screenshots: [
        { label: "Dashboard" },
        { label: "AI Generator" },
        { label: "Projects" },
        { label: "Media Library" },
        { label: "Billing" },
        { label: "Analytics" },
      ],
    },
  },
  {
    id: "realtime-stats-section",
    sectionKey: "realtime-stats",
    type: "custom",
    title: "Platform Statistics",
    description: "Real-time metrics from our production infrastructure.",
    order: 5,
    visible: true,
    config: {
      heading: "Real-time Platform Stats",
      description: "Real-time metrics from our production infrastructure.",
      statItems: [
        { key: "activeUsers", label: "Active Users" },
        { key: "projects", label: "Projects" },
        { key: "aiJobs", label: "AI Jobs" },
        { key: "imagesGenerated", label: "Images Generated" },
        { key: "videosGenerated", label: "Videos Generated" },
        { key: "storageUsed", label: "Storage Used" },
        { key: "apiRequests", label: "API Requests" },
        { key: "queueLength", label: "Queue Length" },
      ],
      stats: [
        { label: "Active Users", value: "5K+", suffix: "+" },
        { label: "AI Jobs", value: "50K/day", suffix: "" },
        { label: "Images Generated", value: "1M+", suffix: "+", display: "1M+" },
        { label: "Videos Generated", value: "100K+", suffix: "+", display: "100K+" },
      ],
    },
  },
  {
    id: "pricing-section",
    sectionKey: "pricing",
    type: "pricing",
    title: "Pricing",
    description: "Simple and transparent pricing for every stage of your production workflow.",
    order: 6,
    visible: true,
    config: {
      heading: "Pricing",
      description: "Simple and transparent pricing for every stage of your production workflow.",
      plans: [
        { name: "Free", priceMonthly: 0, priceYearly: 0, includedCreditsMonthly: 0, includedCreditsYearly: 0, description: "For individuals exploring AI production.", features: ["Platform access", "1 Workspace", "3 Projects", "Basic AI models", "Community support"], cta: "marketing.getStarted", href: "/register" },
        { name: "Starter", priceMonthly: 29, priceYearly: 23, includedCreditsMonthly: 5000, includedCreditsYearly: 60000, description: "For creators getting serious about production.", features: ["Platform access", "5 Workspaces", "Unlimited projects", "All AI providers", "Priority support"], popular: true, cta: "marketing.getStarted", href: "/register" },
        { name: "Pro", priceMonthly: 79, priceYearly: 63, includedCreditsMonthly: 25000, includedCreditsYearly: 300000, description: "For teams shipping content at scale.", features: ["Platform access", "20 Workspaces", "Custom domains", "Advanced analytics", "Dedicated support"], cta: "marketing.getStarted", href: "/register" },
        { name: "Business", priceMonthly: 199, priceYearly: 159, includedCreditsMonthly: 100000, includedCreditsYearly: 1200000, description: "For organizations that need control and compliance.", features: ["Platform access", "Unlimited workspaces", "SSO & SCIM", "Custom integrations", "SLA guarantee"], topUp: true, cta: "marketing.contactSales", href: "/contact" },
        { name: "Enterprise", priceMonthly: null, priceYearly: null, includedCreditsMonthly: -1, includedCreditsYearly: -1, description: "For large-scale deployments with dedicated infrastructure.", features: ["Platform access", "Dedicated infrastructure", "Custom SLA", "On-premise option", "24/7 support"], topUp: true, cta: "marketing.contactSales", href: "/contact" },
      ],
    },
  },
  {
    id: "credit-packs-section",
    sectionKey: "credit-packs",
    type: "credit-packs",
    title: "AI Credit Packages",
    description: "Need more AI? Buy Credit Packs anytime.",
    order: 7,
    visible: true,
    config: {
      heading: "AI Credit Packages",
      description: "Need more AI? Buy Credit Packs anytime.",
      packs: [
        { name: "Starter Pack", credits: 10000, price: 50, description: "Perfect for getting started", href: "/register" },
        { name: "Pro Pack", credits: 50000, price: 200, description: "For growing teams", href: "/register" },
        { name: "Business Pack", credits: 200000, price: 700, description: "For large operations", href: "/register" },
      ],
    },
  },
  {
    id: "credit-calculator-section",
    sectionKey: "credit-calculator",
    type: "custom",
    title: "Credit Calculator",
    description: "Estimate your monthly credit usage and find the right plan.",
    order: 8,
    visible: true,
    config: {
      heading: "Credit Calculator",
      description: "Estimate your monthly credit usage and find the right plan.",
      actions: [
        { key: "creditCalculatorTextGeneration", label: "Text generation", credits: 1 },
        { key: "creditCalculatorImageGeneration", label: "Image generation", credits: 5 },
        { key: "creditCalculatorVideoGeneration", label: "Video generation", credits: 50 },
        { key: "creditCalculatorAudioGeneration", label: "Audio generation", credits: 10 },
        { key: "creditCalculatorCustomPrompt", label: "Custom prompt / workflow", credits: 2 },
      ],
    },
  },
  {
    id: "credit-usage-section",
    sectionKey: "credit-usage",
    type: "credit-usage",
    title: "AI Credit Usage",
    description: "Estimated cost of credits per AI action. Actual costs may vary depending on model and parameters.",
    order: 9,
    visible: true,
    config: {
      heading: "AI Credit Usage",
      description: "Estimated cost of credits per AI action. Actual costs may vary depending on model and parameters.",
      rows: [
        { action: "Short text / chat", model: "GPT-4o", credits: 1, note: "Per message" },
        { action: "Long article / workflow", model: "GPT-4o", credits: 3, note: "Per generation" },
        { action: "Standard image", model: "DALL-E 3", credits: 5, note: "Per image" },
        { action: "HD image", model: "DALL-E 3", credits: 10, note: "Per image" },
        { action: "Short video (15s)", model: "Runway", credits: 50, note: "Per video" },
        { action: "Long video (60s)", model: "Runway", credits: 150, note: "Per video" },
        { action: "TTS / voiceover", model: "ElevenLabs", credits: 10, note: "Per minute" },
        { action: "Music / SFX", model: "MusicGen", credits: 15, note: "Per track" },
        { action: "Custom model call", model: "Any", credits: "Varies", note: "Per API call" },
        { action: "Batch processing", model: "Any", credits: "Varies", note: "Per batch" },
      ],
    },
  },
  {
    id: "testimonials-section",
    sectionKey: "testimonials",
    type: "custom",
    title: "Loved by production teams",
    description: "See how teams use Tamer Studio to move from intent to production.",
    order: 10,
    visible: true,
    config: {
      heading: "Loved by production teams",
      description: "See how teams use Tamer Studio to move from intent to production.",
      testimonials: [
        { quote: "Tamer Studio transformed how our team produces content. The AI integrations are seamless, and the workflow automation saved us hours every week.", author: "Sarah Chen", role: "Head of Content", company: "Studio North" },
        { quote: "We reduced production time by 60% after switching to Tamer Studio. The multi-provider AI platform is exactly what we needed.", author: "Marcus Rivera", role: "Creative Director", company: "Atlas Agency" },
        { quote: "The credit system is transparent and the billing is predictable. Finally, an AI platform that treats costs seriously.", author: "Aiko Tanaka", role: "CTO", company: "Pixel Foundry" },
      ],
    },
  },
  {
    id: "faq-section",
    sectionKey: "faq",
    type: "faq",
    title: "Frequently Asked Questions",
    description: "Everything you need to know about Tamer Studio.",
    order: 11,
    visible: true,
    config: {
      heading: "Frequently Asked Questions",
      description: "Everything you need to know about Tamer Studio.",
      items: [
        { question: "How does billing work?", answer: "Tamer Studio uses a credit-based billing system. You purchase credits and consume them when running AI jobs, generating media, or using production features." },
        { question: "Which AI models are supported?", answer: "We support OpenAI (GPT-4, GPT-4o), Google Gemini, Anthropic Claude, OpenRouter, Kilo, and more. New providers are added regularly." },
        { question: "How is my data protected?", answer: "Your data is encrypted at rest and in transit. We do not use your data to train models. SOC 2 Type II compliant." },
        { question: "Is Tamer Studio secure?", answer: "Yes. We use industry-standard encryption, role-based access control, audit logging, and regular security assessments." },
      ],
    },
  },
  {
    id: "cta-section",
    sectionKey: "cta",
    type: "cta",
    title: "Ready to Transform Your Workflow?",
    description: "Create your account and bring your team into the AI-first production environment.",
    order: 12,
    visible: true,
    config: {
      heading: "Ready to Transform Your Workflow?",
      description: "Create your account and bring your team into the AI-first production environment.",
      ctaPrimary: "Get Started Free",
      ctaSecondary: "Schedule Demo",
      note: "No credit card required. Start building today.",
    },
  },
  {
    id: "footer-section",
    sectionKey: "footer",
    type: "footer",
    title: "Footer",
    description: null,
    order: 13,
    visible: true,
    config: {
      companyName: "Tamer Studio",
      tagline: "From intent to production.",
      links: {
        product: [
          { label: "Features", href: "#features" },
          { label: "Pricing", href: "#pricing" },
          { label: "Roadmap", href: "/roadmap" },
          { label: "Documentation", href: "/docs" },
          { label: "API", href: "/docs" },
          { label: "Developers", href: "/docs" },
        ],
        resources: [
          { label: "Blog", href: "/blog" },
          { label: "Community", href: "/blog" },
          { label: "Discord", href: "https://discord.gg/tamerstudio", external: true },
          { label: "GitHub", href: "https://github.com/tamerstudio", external: true },
        ],
        company: [
          { label: "About", href: "/about" },
          { label: "Careers", href: "/careers" },
          { label: "Press", href: "/about" },
          { label: "Partners", href: "/about" },
        ],
        legal: [
          { label: "Privacy Policy", href: "/legal/privacy" },
          { label: "Terms of Service", href: "/legal/terms" },
          { label: "Cookie Policy", href: "/legal/privacy" },
          { label: "Security", href: "/about" },
          { label: "Compliance", href: "/about" },
        ],
      },
    },
  },
];
