CREATE INDEX IF NOT EXISTS "user_profile_status_created_idx" ON "user_profile" USING btree ("status", "created_at");
CREATE INDEX IF NOT EXISTS "workspace_owner_status_idx" ON "workspace" USING btree ("owner_id", "status");
CREATE INDEX IF NOT EXISTS "invoice_workspace_status_idx" ON "invoice" USING btree ("workspace_id", "status");
CREATE INDEX IF NOT EXISTS "subscription_workspace_status_idx" ON "subscription" USING btree ("workspace_id", "status");
CREATE INDEX IF NOT EXISTS "usage_workspace_created_idx" ON "usage_record" USING btree ("workspace_id", "created_at");
CREATE INDEX IF NOT EXISTS "notification_user_status_idx" ON "notification" USING btree ("user_id", "status");
CREATE INDEX IF NOT EXISTS "audit_log_action_created_idx" ON "audit_log" USING btree ("action", "created_at");
CREATE INDEX IF NOT EXISTS "workspace_member_role_id_idx" ON "workspace_member" USING btree ("role_id");
CREATE INDEX IF NOT EXISTS "workspace_member_invited_by_idx" ON "workspace_member" USING btree ("invited_by");
CREATE INDEX IF NOT EXISTS "organization_member_role_id_idx" ON "organization_member" USING btree ("role_id");
CREATE INDEX IF NOT EXISTS "invoice_subscription_id_idx" ON "invoice" USING btree ("subscription_id");
CREATE INDEX IF NOT EXISTS "usage_user_id_idx" ON "usage_record" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "usage_model_id_idx" ON "usage_record" USING btree ("model_id");
CREATE INDEX IF NOT EXISTS "usage_capability_id_idx" ON "usage_record" USING btree ("capability_id");
CREATE INDEX IF NOT EXISTS "cost_record_capability_idx" ON "cost_record" USING btree ("capability_id");
CREATE INDEX IF NOT EXISTS "payment_intent_checkout_session_idx" ON "payment_intent" USING btree ("checkout_session_id");
CREATE INDEX IF NOT EXISTS "support_ticket_workspace_id_idx" ON "support_ticket" USING btree ("workspace_id");
CREATE INDEX IF NOT EXISTS "notification_scheduled_at_idx" ON "notification" USING btree ("scheduled_at");
CREATE INDEX IF NOT EXISTS "event_queue_next_attempt_idx" ON "event_queue" USING btree ("next_attempt_at");
CREATE INDEX IF NOT EXISTS "asset_source_prompt_idx" ON "asset" USING btree ("source_prompt_id");
CREATE INDEX IF NOT EXISTS "asset_source_gateway_idx" ON "asset" USING btree ("source_gateway_id");
CREATE INDEX IF NOT EXISTS "asset_source_capability_idx" ON "asset" USING btree ("source_capability_id");