import {
  type SupportedLocale,
  type SupportedCurrency,
  type CountryInfo,
  SUPPORTED_LOCALES,
  DEFAULT_LOCALE,
  DEFAULT_CURRENCY,
} from "./types";
import { SUPPORTED_CURRENCIES } from "../currency/constants";

export const COUNTRY_MAP: Record<string, CountryInfo> = {
  ID: {
    code: "ID",
    name: "Indonesia",
    nativeName: "Indonesia",
    locale: "id",
    currency: "IDR",
    timezone: "Asia/Jakarta",
    phoneCode: "+62",
  },
  US: {
    code: "US",
    name: "United States",
    nativeName: "United States",
    locale: "en",
    currency: "USD",
    timezone: "America/New_York",
    phoneCode: "+1",
  },
  GB: {
    code: "GB",
    name: "United Kingdom",
    nativeName: "United Kingdom",
    locale: "en",
    currency: "USD",
    timezone: "Europe/London",
    phoneCode: "+44",
  },
  SG: {
    code: "SG",
    name: "Singapore",
    nativeName: "Singapore",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Singapore",
    phoneCode: "+65",
  },
  MY: {
    code: "MY",
    name: "Malaysia",
    nativeName: "Malaysia",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Kuala_Lumpur",
    phoneCode: "+60",
  },
  TH: {
    code: "TH",
    name: "Thailand",
    nativeName: "Thailand",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Bangkok",
    phoneCode: "+66",
  },
  PH: {
    code: "PH",
    name: "Philippines",
    nativeName: "Philippines",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Manila",
    phoneCode: "+63",
  },
  VN: {
    code: "VN",
    name: "Vietnam",
    nativeName: "Vietnam",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Ho_Chi_Minh",
    phoneCode: "+84",
  },
  AE: {
    code: "AE",
    name: "United Arab Emirates",
    nativeName: "United Arab Emirates",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Dubai",
    phoneCode: "+971",
  },
  SA: {
    code: "SA",
    name: "Saudi Arabia",
    nativeName: "Saudi Arabia",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Riyadh",
    phoneCode: "+966",
  },
  DE: {
    code: "DE",
    name: "Germany",
    nativeName: "Deutschland",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Berlin",
    phoneCode: "+49",
  },
  FR: {
    code: "FR",
    name: "France",
    nativeName: "France",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Paris",
    phoneCode: "+33",
  },
  JP: {
    code: "JP",
    name: "Japan",
    nativeName: "日本",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Tokyo",
    phoneCode: "+81",
  },
  KR: {
    code: "KR",
    name: "South Korea",
    nativeName: "대한민국",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Seoul",
    phoneCode: "+82",
  },
  CN: {
    code: "CN",
    name: "China",
    nativeName: "中国",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Shanghai",
    phoneCode: "+86",
  },
  IN: {
    code: "IN",
    name: "India",
    nativeName: "भारत",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Kolkata",
    phoneCode: "+91",
  },
  AU: {
    code: "AU",
    name: "Australia",
    nativeName: "Australia",
    locale: "en",
    currency: "USD",
    timezone: "Australia/Sydney",
    phoneCode: "+61",
  },
  CA: {
    code: "CA",
    name: "Canada",
    nativeName: "Canada",
    locale: "en",
    currency: "USD",
    timezone: "America/Toronto",
    phoneCode: "+1",
  },
  BR: {
    code: "BR",
    name: "Brazil",
    nativeName: "Brasil",
    locale: "en",
    currency: "USD",
    timezone: "America/Sao_Paulo",
    phoneCode: "+55",
  },
  MX: {
    code: "MX",
    name: "Mexico",
    nativeName: "México",
    locale: "en",
    currency: "USD",
    timezone: "America/Mexico_City",
    phoneCode: "+52",
  },
  RU: {
    code: "RU",
    name: "Russia",
    nativeName: "Россия",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Moscow",
    phoneCode: "+7",
  },
  NL: {
    code: "NL",
    name: "Netherlands",
    nativeName: "Nederland",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Amsterdam",
    phoneCode: "+31",
  },
  ES: {
    code: "ES",
    name: "Spain",
    nativeName: "España",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Madrid",
    phoneCode: "+34",
  },
  IT: {
    code: "IT",
    name: "Italy",
    nativeName: "Italia",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Rome",
    phoneCode: "+39",
  },
  SE: {
    code: "SE",
    name: "Sweden",
    nativeName: "Sverige",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Stockholm",
    phoneCode: "+46",
  },
  NO: {
    code: "NO",
    name: "Norway",
    nativeName: "Norge",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Oslo",
    phoneCode: "+47",
  },
  DK: {
    code: "DK",
    name: "Denmark",
    nativeName: "Danmark",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Copenhagen",
    phoneCode: "+45",
  },
  FI: {
    code: "FI",
    name: "Finland",
    nativeName: "Suomi",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Helsinki",
    phoneCode: "+358",
  },
  PL: {
    code: "PL",
    name: "Poland",
    nativeName: "Polska",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Warsaw",
    phoneCode: "+48",
  },
  TR: {
    code: "TR",
    name: "Turkey",
    nativeName: "Türkiye",
    locale: "en",
    currency: "USD",
    timezone: "Europe/Istanbul",
    phoneCode: "+90",
  },
  ZA: {
    code: "ZA",
    name: "South Africa",
    nativeName: "South Africa",
    locale: "en",
    currency: "USD",
    timezone: "Africa/Johannesburg",
    phoneCode: "+27",
  },
  NG: {
    code: "NG",
    name: "Nigeria",
    nativeName: "Nigeria",
    locale: "en",
    currency: "USD",
    timezone: "Africa/Lagos",
    phoneCode: "+234",
  },
  EG: {
    code: "EG",
    name: "Egypt",
    nativeName: "مصر",
    locale: "en",
    currency: "USD",
    timezone: "Africa/Cairo",
    phoneCode: "+20",
  },
  IL: {
    code: "IL",
    name: "Israel",
    nativeName: "ישראל",
    locale: "en",
    currency: "USD",
    timezone: "Asia/Jerusalem",
    phoneCode: "+972",
  },
};

export function getCountryInfo(countryCode: string): CountryInfo {
  return COUNTRY_MAP[countryCode.toUpperCase()] || {
    code: countryCode.toUpperCase(),
    name: countryCode.toUpperCase(),
    nativeName: countryCode.toUpperCase(),
    locale: DEFAULT_LOCALE,
    currency: DEFAULT_CURRENCY,
    timezone: "UTC",
    phoneCode: "",
  };
}

export function getLocaleFromCountry(countryCode: string): SupportedLocale {
  const info = getCountryInfo(countryCode);
  return SUPPORTED_LOCALES[info.locale] ? info.locale : DEFAULT_LOCALE;
}

export function getCurrencyFromCountry(countryCode: string): SupportedCurrency {
  const info = getCountryInfo(countryCode);
  return SUPPORTED_CURRENCIES[info.currency] ? info.currency : DEFAULT_CURRENCY;
}

export function getTimezoneFromCountry(countryCode: string): string {
  const info = getCountryInfo(countryCode);
  return info.timezone;
}
