import { getNavigationRuntime } from "./navigation-runtime";
import type { RegisterNavigationInput } from "./navigation.types";

const sidebarItems: RegisterNavigationInput[] = [
  {
    id: "sidebar.dashboard",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Dashboard",
    titleKey: "dashboard.dashboard",
    route: "/dashboard",
    icon: "Home",
    order: 0,
    group: "main",
  },
  {
    id: "sidebar.workspace",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Workspace",
    titleKey: "dashboard.workspace",
    route: "/workspace",
    icon: "Grid",
    order: 1,
    group: "main",
  },
  {
    id: "sidebar.projects",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Projects",
    titleKey: "dashboard.projects",
    route: "/projects",
    icon: "Folder",
    order: 2,
    group: "main",
  },
  {
    id: "sidebar.media",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Media",
    titleKey: "dashboard.media",
    route: "/media",
    icon: "ImageIcon",
    order: 3,
    group: "main",
  },
  {
    id: "sidebar.production",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Production",
    titleKey: "dashboard.production",
    route: "/production",
    icon: "Film",
    order: 4,
    group: "main",
  },
  {
    id: "sidebar.ai",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "AI",
    titleKey: "dashboard.ai",
    route: "/ai",
    icon: "Cpu",
    order: 5,
    group: "main",
  },
  {
    id: "sidebar.publishing",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Publishing",
    titleKey: "dashboard.publishing",
    route: "/publishing",
    icon: "FileText",
    order: 6,
    group: "main",
  },
  {
    id: "sidebar.settings",
    module: "dashboard",
    position: "sidebar",
    type: "page",
    title: "Settings",
    titleKey: "dashboard.settings",
    route: "/settings",
    icon: "Settings",
    order: 7,
    group: "manage",
  },
];

const adminSidebarItems: RegisterNavigationInput[] = [
  {
    id: "admin.dashboard",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Admin Dashboard",
    titleKey: "admin.dashboard",
    route: "/admin",
    icon: "LayoutDashboard",
    order: 0,
    group: "dashboard",
  },
  {
    id: "admin.users",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Users",
    titleKey: "admin.users",
    route: "/admin/users",
    icon: "Users",
    order: 1,
    group: "management",
    permissions: ["admin:users"],
  },
  {
    id: "admin.organizations",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Organizations",
    titleKey: "admin.organizations",
    route: "/admin/organizations",
    icon: "Building2",
    order: 2,
    group: "management",
    permissions: ["admin:organizations"],
  },
  {
    id: "admin.workspaces",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Workspaces",
    titleKey: "admin.workspaces",
    route: "/admin/workspaces",
    icon: "Workflow",
    order: 3,
    group: "management",
    permissions: ["admin:workspaces"],
  },
  {
    id: "admin.ai-providers",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "AI Providers",
    titleKey: "admin.aiProviders",
    route: "/admin/ai-providers",
    icon: "Cpu",
    order: 4,
    group: "management",
    permissions: ["admin:ai_providers"],
  },
  {
    id: "admin.landing-builder",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Landing Builder",
    titleKey: "admin.landingBuilder",
    route: "/admin/landing-builder",
    icon: "LayoutTemplate",
    order: 5,
    group: "management",
    permissions: ["admin:landing_builder"],
  },
  {
    id: "admin.jobs",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Jobs",
    titleKey: "admin.jobs",
    route: "/admin/jobs",
    icon: "Rocket",
    order: 6,
    group: "management",
    permissions: ["admin:jobs"],
  },
  {
    id: "admin.queues",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Queues",
    titleKey: "admin.queues",
    route: "/admin/queues",
    icon: "BarChart3",
    order: 7,
    group: "management",
    permissions: ["admin:queues"],
  },
  {
    id: "admin.billing",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Billing",
    titleKey: "admin.billing.label",
    route: "/admin/billing",
    icon: "CreditCard",
    order: 8,
    group: "management",
    permissions: ["admin:billing"],
  },
  {
    id: "admin.subscriptions",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Subscriptions",
    titleKey: "admin.subscriptions.label",
    route: "/admin/subscriptions",
    icon: "Ticket",
    order: 9,
    group: "management",
    permissions: ["admin:subscriptions"],
  },
  {
    id: "admin.coupons",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Coupons",
    titleKey: "admin.coupons.label",
    route: "/admin/coupons",
    icon: "Ticket",
    order: 10,
    group: "management",
    permissions: ["admin:coupons"],
  },
  {
    id: "admin.analytics",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Analytics",
    titleKey: "admin.analytics.label",
    route: "/admin/analytics",
    icon: "LineChart",
    order: 11,
    group: "analytics",
    permissions: ["admin:analytics"],
  },
  {
    id: "admin.audit-logs",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Audit Logs",
    titleKey: "admin.auditLogs.label",
    route: "/admin/audit-logs",
    icon: "ScrollText",
    order: 12,
    group: "analytics",
    permissions: ["admin:audit_logs"],
  },
  {
    id: "admin.feature-flags",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Feature Flags",
    titleKey: "admin.featureFlags.label",
    route: "/admin/feature-flags",
    icon: "Flag",
    order: 13,
    group: "analytics",
    permissions: ["admin:feature_flags"],
  },
  {
    id: "admin.settings",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Settings",
    titleKey: "admin.settings",
    route: "/admin/settings",
    icon: "Settings",
    order: 14,
    group: "settings",
    permissions: ["admin:system"],
  },
  {
    id: "admin.email",
    module: "admin",
    position: "admin-sidebar",
    type: "page",
    title: "Email",
    titleKey: "admin.email",
    route: "/admin/email",
    icon: "Mail",
    order: 15,
    group: "settings",
    permissions: ["admin:email"],
  },
];

const headerItems: RegisterNavigationInput[] = [
  {
    id: "header.notifications",
    module: "core",
    position: "header",
    type: "page",
    title: "Notifications",
    titleKey: "header.notifications",
    route: "/notifications",
    icon: "Bell",
    order: 0,
  },
  {
    id: "header.profile",
    module: "core",
    position: "header",
    type: "page",
    title: "Profile",
    titleKey: "header.profile",
    route: "/settings/profile",
    icon: "UserCircle",
    order: 1,
  },
  {
    id: "header.search",
    module: "core",
    position: "header",
    type: "page",
    title: "Search",
    titleKey: "header.search",
    route: "/search",
    icon: "Search",
    order: 2,
  },
  {
    id: "header.help",
    module: "core",
    position: "header",
    type: "page",
    title: "Help",
    titleKey: "header.help",
    route: "/help",
    icon: "HelpCircle",
    order: 3,
  },
];

const footerItems: RegisterNavigationInput[] = [
  {
    id: "footer.home",
    module: "core",
    position: "footer",
    type: "page",
    title: "Home",
    titleKey: "footer.home",
    route: "/",
    icon: "Home",
    order: 0,
  },
  {
    id: "footer.about",
    module: "core",
    position: "footer",
    type: "page",
    title: "About",
    titleKey: "footer.about",
    route: "/about",
    icon: "Info",
    order: 1,
  },
  {
    id: "footer.contact",
    module: "core",
    position: "footer",
    type: "page",
    title: "Contact",
    titleKey: "footer.contact",
    route: "/contact",
    icon: "Mail",
    order: 2,
  },
  {
    id: "footer.privacy",
    module: "core",
    position: "footer",
    type: "page",
    title: "Privacy Policy",
    titleKey: "footer.privacy",
    route: "/privacy",
    icon: "Shield",
    order: 3,
  },
  {
    id: "footer.terms",
    module: "core",
    position: "footer",
    type: "page",
    title: "Terms of Service",
    titleKey: "footer.terms",
    route: "/terms",
    icon: "FileText",
    order: 4,
  },
];

let bootstrapped = false;

export function bootstrapNavigation(): void {
  if (bootstrapped) return;
  bootstrapped = true;

  const runtime = getNavigationRuntime();

  for (const item of sidebarItems) {
    runtime.registerItem(item);
  }
  for (const item of adminSidebarItems) {
    runtime.registerItem(item);
  }
  for (const item of headerItems) {
    runtime.registerItem(item);
  }
  for (const item of footerItems) {
    runtime.registerItem(item);
  }
}

export function resetBootstrap(): void {
  bootstrapped = false;
}
